todo_SOA/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nancy.Json;
using todo_SOA.Models;
namespace todo_SOA.Controllers
{
    public class TasksController : Controller
    {
        public string userID = "";
        public string serverEndPoin = "http://192.168.1.45:8081";
        // GET: Tasks
        public async Task<ActionResult> IndexAsync()
        {
            // Lưu trữ thông tin tạm của chương trình
            this.userID = Convert.ToString(TempData["UserID"]);
            ViewBag.UserName = TempData["UserName"];
            TempData.Keep();
            ViewBag.UserID = TempData["UserID"];
            TempData.Keep();
            ViewBag.Login = (userID == "") ? false : true;
            string url = serverEndPoin + "/tasks";

            // Khởi tạo http client
            HttpClient httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Add("Authorization", userID);
            // Get data
            var response = await httpClient.GetAsync(url);
            var responseContent = await response.Content.ReadAsStringAsync();
            var status = response.StatusCode;

            // Chuyển sang object 
            JavaScriptSerializer j = new JavaScriptSerializer();
            var obj = j.Deserialize<dynamic>(responseContent);
            List<TaskDT> listTask = new List<TaskDT>();
            foreach (var item in obj["data"])
            {
                TaskDT temp = new TaskDT();
                temp.Id = item["id"];
                temp.Name = item["name"];
                temp.DueTime = item["dueTime"];
                temp.Status = item["status"];
                temp.Tag = item["tagsList"][0]["name"];
                listTask.Add(temp);
            }
            ViewBag.DataSource = listTask;
            switch (status)
            {
                case System.Net.HttpStatusCode.OK:
                    ViewBag.Status = "Get list Successfull";
                    ViewBag.UserId = userID;
                    break;
                case System.Net.HttpStatusCode.BadRequest:
                    ViewBag.Status = "Get list UNSuccessfull";
                    string Res = "";
                    if (obj["reasons"] != null)
                    {
                        foreach (var item in obj["reasons"])
                        {
                            Res = Res + "\n" + item["path"] + " : " + item["message"];
                        }
                    }
                    ViewBag.Message = obj["message"] + "\n" + Res;
                    break;
                case System.Net.HttpStatusCode.RequestTimeout:
                    ViewBag.Status = "Get list UNSuccessfull";
                    ViewBag.Message = "RequestTimeout";
                    break;
                case System.Net.HttpStatusCode.InternalServerError:
                    ViewBag.Status = "Get list UNSuccessfull";
                    ViewBag.Message = "InternalServerError";
                    break;
                default:
                    ViewBag.Message = obj["message"];
                    break;
            }
            return View();
        }


        public ActionResult Error(dynamic ViewBag)
        {

            return View(ViewBag);
        }

        // GET: Tasks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync(IFormCollection collection)
        {
            ViewBag.Login = (userID == "") ? false : true;

            try
            {
                this.userID = Convert.ToString(TempData["UserID"]);
                ViewBag.UserName = TempData["UserName"];
                TempData.Keep();
                var httpClient = new HttpClient();

                string url = serverEndPoin + "/tasks";
                string name = collection["name"];
                string description = collection["description"];
                string dueTime = DateTime.Parse(collection["duetime"]).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.sssZ");
                string tag = collection["tags"];
                // Khởi tạo http client
                var httpRequestMessage = new HttpRequestMessage
                {
                    Method = HttpMethod.Post,
                    RequestUri = new Uri(url)
                };
                // Tạo StringContent
                string jsoncontent = "{\"taskName\": \"" + name + "\", \"description\": \"" + description + "\", \"dueTime\": \"" + dueTime + "\", \"tags\": [\"" + tag + "\"]}";
                var httpContent = new StringContent(jsoncontent, Encoding.UTF8, "application/json");
                httpRequestMessage.Content = httpContent;
                httpClient.DefaultRequestHeaders.Add("Authorization", userID);
                // call api
                var response = await httpClient.SendAsync(httpRequestMessage);
                var responseContent = await response.Content.ReadAsStringAsync();
                var status = response.StatusCode;
                ViewBag.Message = responseContent;
                // Chuyển sang object 
                JavaScriptSerializer j = new JavaScriptSerializer();
                var obj = j.Deserialize<dynamic>(responseContent);


                switch (status)
                {
                    case System.Net.HttpStatusCode.OK:
                        ViewBag.Message = "Created";
                        break;
                    case System.Net.HttpStatusCode.Unauthorized:
                        break;
                    case System.Net.HttpStatusCode.Created:
                        ViewBag.Message = "New Task Created";
                        break;
                    case System.Net.HttpStatusCode.BadRequest:
                        string Res = "";
                        if (obj["reasons"] != null)
                        {
                            foreach (var item in obj["reasons"])
                            {
                                Res = Res + "\n" + item["path"] + " : " + item["message"];
                            }
                        }
                        ViewBag.Message = obj["message"] + "\n" + Res;
                        break;
                    case System.Net.HttpStatusCode.RequestTimeout:
                        ViewBag.Message = "RequestTimeout";
                        break;
                    case System.Net.HttpStatusCode.InternalServerError:
                        ViewBag.Message = "InternalServerError";
                        break;
                    default:
                        ViewBag.Message = obj["message"];
                        break;
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message.ToString();
                ViewBag.Status = "Can't Create Task !!!";

                return Redirect(Error(ViewBag));
            }
        }

        public async Task<ActionResult> DetailAsync(string id)
        {
            ViewBag.Login = (userID == "") ? false : true;
            try
            {
                // lưu trữ và truy xuất thông tin biến tạm tại Client
                this.userID = Convert.ToString(TempData["UserID"]);
                ViewBag.UserName = TempData["UserName"];
                TempData.Keep();
                ViewBag.UserID = TempData["UserID"];
                TempData.Keep();
                ViewBag.Login = (userID == "") ? false : true;
                string url = serverEndPoin + "/tasks/" + id;

                // Khởi tạo http client
                HttpClient httpClient = new HttpClient();
                httpClient.DefaultRequestHeaders.Add("Authorization", userID);
                // Get data
                var response = await httpClient.GetAsync(url);
                var responseContent = await response.Content.ReadAsStringAsync();
                var status = response.StatusCode;
                // Chuyển sang object 
                JavaScriptSerializer j = new JavaScriptSerializer();
                var obj = j.Deserialize<dynamic>(responseContent);

                switch (status)
                {
                    case System.Net.HttpStatusCode.OK:
                        ViewBag.Status = "Get list Successfull";
                        ViewBag.UserId = userID;
                        Models.Task result = new Models.Task(obj["data"]["id"], obj["data"]["name"], obj["data"]["description"], obj["data"]["dueTime"], obj["data"]["status"], obj["data"]["tagsList"][0]["name"]);
                        return View(result);
                    case System.Net.HttpStatusCode.BadRequest:
                        ViewBag.Status = "Get list UNSuccessfull";
                        string Res = "";
                        if (obj["reasons"] != null)
                        {
                            foreach (var item in obj["reasons"])
                            {
                                Res = Res + "\n" + item["path"] + " : " + item["message"];
                            }
                        }
                        ViewBag.Message = obj["message"] + "\n" + Res;
                        break;
                    case System.Net.HttpStatusCode.RequestTimeout:
                        ViewBag.Status = "Get list UNSuccessfull";
                        ViewBag.Message = "RequestTimeout";
                        break;
                    case System.Net.HttpStatusCode.InternalServerError:
                        ViewBag.Status = "Get list UNSuccessfull";
                        ViewBag.Message = "InternalServerError";
                        break;
                    default:

todo_SOA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - todo_SOA</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Index">MyTask</a>
                        </li>
                    </ul>
                </div>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - todo_SOA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>